### ISSUE TITLE
WTF next

### ISSUE THREAD

**Issue by binarymason** [rollyourownruby/rollyourownruby#1]
The **purpose** of this issue is to clarify on what the most impactful application of effort would be to **grow the junior Charlotte ruby community (_to become more employable_)**.

<hr>

What that purpose in my mind, there a few obvious questions that come to mind.

1.  What are the things that the growing junior ruby community in Charlotte _needs_? 
2.  Out of those things, what need would be most helpful if addressed?
3.  How can we most effectively address that need?
4.  What things should we consider to make things sustainable in order to avoid burnout?
5.  What would be the most effective time/place for a meetup?

<hr>

Here's my initial stab at the questions above:

> 1.  What are the things that the growing junior ruby community in Charlotte _needs_? 

Fun, Mentorship, Sense of Community, Resources, Jobs, Continuing Education

> 2. Out of those things, what need would be most helpful if addressed?

I think the most impactful things would be in this order: Mentorship, Fun, Jobs 

> 3.  How can we most effectively address that need?

* Having a regular meetup with regular problems to solve.  Challenges are a must. Maybe have a mixture of live demos and/or pair programming.

* Grow reputation and network to have a pulse on jobs; become a place recruiters go to for ruby candidates; be able to give recommendations to potential employers.

> 4. What things should we consider to make things sustainable in order to avoid burnout?

* Frequency of meetups
* Keeping regular content/challenges going

> 5.  What would be the most effective time/place for a meetup?

I think Skookum would keep things consistent.  With a once a month meetup already going, I think we could do an additional two meetups a month at the exact same time `7-9`.  With real world projects, I tend to think every week would be better, but I'm concerned about burnout.

**Comment by kirillian** [comment]
I definitely agree with a lot of these things. I think one of the biggest issues facing Charlotte's community is that we have a lot of very advanced Rubyists and a lot of juniors, but either there aren't very many middling skill level developers or they aren't showing up for meetings. Seniors will often find it difficult to connect with juniors for lots of reasons.

This can make the two groups difficult to mesh. I don't think we're doing poorly considering what we have, but I agree that by increasing the amount of engagement we have, we can not only draw more of that community in, but also draw in the businesses and employers. I'm OFTEN asked to recommend people to recruiters, but, without the chance to show what they can do at our meetups, I am unable to really give real recommendations. I usually tell the recruiters that they can attend, but I don't think I've actually ever seen that happen.

> I think the most impactful things would be in this order: Mentorship, Fun, Jobs

I think that getting mentorship will be slow, but it will only increase as the community grows and positive feedback for their efforts comes in. Fun comes from a positive feedback loop in my experience, and the jobs exist. In fact, places are trying to find people quite often, but they often can't find people and so turn to remote workers or other languages or otherwise.

> Having a regular meetup with regular problems to solve. Challenges are a must. Maybe have a mixture of live demos and/or pair programming.
> 
> Grow reputation and network to have a pulse on jobs; become a place recruiters go to for ruby candidates; be able to give recommendations to potential employers.

I agree wholeheartedly with both of these. We saw our numbers swell a bit when we were doing problems and I loved what they were doing in Raleigh when I visited a couple times. Doing those problems on a monthly basis at a minimum would be good. We can then invite them to chill at the regular meetup as more of a social thing - or we give the regular meetup its sort of theme as well. I think once we have the audience, talks will more readily come in. It's tough to prep a talk and then have no audience.

I would personally be willing to help lead the challenge thing as long as I had a partner to spell me (I know from experience that that kind of thing gets old fast without help).

exercism.io is a FANTASTIC choice for doing those problems. We could also tap the West Side Ruby group in the Triangle for their experiences too.

I also have some work appropriate for all levels - I have a customer that needs a Rails upgrade done this spring/summer and its a rather large project with a missing test suite. So there is a lot of room for adding tests and doing small chunks under mentorship. I would GLADLY bring that to the table if it was interesting to people.

**Comment by kirillian** [comment]
I would also recommend that we pick up the slack on taking care of Impressionist while we're at it.

https://github.com/charlotte-ruby/impressionist/pulls

**Comment by binarymason** [comment]
Alright, I think the way ahead is definitely to focus on problems and challenges.  If you want to take lead on that great, I am also more than happy to support.

Here are the next actions I see from my angle (ordered as best as possible):

- Clarify frequency
In the name of avoiding burnout, but also keeping things going I recommend having the original meetup and two additional meetups focused on the junior crowd maximum. If we introduce real world projects with deadlines, I think two additional meetups is a must.

- Start a Slack channel
This will keep things going in between meetups.

- Clarify location: 
I talked to @chowie2 and he gave strong indications that Skookum would support. @chowie2, can you confirm?

- Start a problem/challenge backlog somewhere (GH or Trello?)
The larger the backlog, the less stressful it will be to come up with content, IMO.  If it's open source, people could make specific requests as well.

- Make the schedule on meetup.com ✨ 

- Spread the word
I am happy to take the lead on this, asking for as much help as possible from the people I know.

**Comment by binarymason** [comment]
cc @chrishowie. He has two accounts apparently 😜

**Comment by chrishowie** [comment]
Yeah I am a fan of the unexpected account @binarymason haha

**Comment by chrishowie** [comment]
@binarymason Could you give me an idea around the "Original Meetup"? Where is it currently located at? 

Slack Channel
+1 

Clarify Frequency 
When you say real world projects, where are these coming from? Are they personal projects or something else? 

Location
Also going forward with location, I can ask about getting us on the schedule here at Skookum. However what time do your meetups generally happen? 

Problem Tracking
I think keeping everything in one spot will make more sense. So using GitHub as the platform would help. Trello also just got bought out by Jira, so it's possible the free service could go away. Also what kind of problems would you be tracking? 

Meetup.com
I believe their is a fee associated to meetup. Not sure the cost, but who would fund that? 

Spread the word
I could do this at our various meetups. Also I host a Tech Career Exploration at the library. So if either of you would be willing to come speak at that it could get the word out. 
I can also speak with the community organizers of Tech Talent South and The Iron Yard at some point.

**Comment by binarymason** [comment]
@chrishowie 

The original meetup is https://www.meetup.com/charlotte-rb/ which is the first Tuesday of every month.

Slack channel created here --> https://charlotte-ruby.slack.com/
Invite link is here (only good for a week) --> https://charlotteruby.slack.com/shared_invite/MTU0MTU0MjU5NzM1LTE0ODk0MTExODYtMDFhMGEzY2IwOQ

> When you say real world projects, where are these coming from? Are they personal projects or something else?
Could be both. @kirillian has some client work that he could bring.

> Problem Tracking
Ok, I think GitHub is also the way to go.  We should probably keep things consistent with `charlotte-ruby` though.  Any way you can get Matt to create `challenges` repo on https://github.com/charlotte-ruby, @kirillian?  We could make issues for future challenges and hang up source code for past challenges, if applicable.

> I believe there is a fee associated to meetup. Not sure the cost, but who would fund that?
I believe the current organizer, Matt is still paying 💰. We should be good there.

> I could do this at our various meetups. Also I host a Tech Career Exploration at the library. So if either of you would be willing to come speak at that it could get the word out.
I can also speak with the community organizers of Tech Talent South and The Iron Yard at some point.
Heck yeah!  You _do_ happen to know almost everybody. 😉  Once we get the dates on the calendar, let's get together to sync up on this.

**Comment by kirillian** [comment]
@binarymason and @chrishowie Yes, I have a client project that guys with some experience, but not a lot could handle in that I have a long runway to upgrade a client app from Rails 3 to 5 and a lot of it is going to be repeatable changes. There is some work there that would be paying, but its also not never-ending by any means.

I actually can create that repo as I'm one of the admins. We could probably also get matt in here to chat(@invalidusrname). Matt IS still paying currently, though I offered to split/front costs with him a couple months ago.

I would also second leaving everything in one place. Having a slack channel is one thing, but we should probably keep all issues in Github too...

Regarding giving a talk, what kind of content are you looking for?

**Comment by invalidusrname** [comment]
So here's a few things we've tried at hack nights we it comes to projects:

[exercism.io](http://exercism.io)
[rubyquiz](http://rubyquiz.com)
[rubykoans](http://rubykoans.com)
[projecteuler](https://projecteuler.net)

They've had varying levels of interest. Sometimes the topics were too hard. Other times a few hours of work is hard for people to commit to. That being said, we tried a few things that I can share:

First was let someone drive a problem from start to finish during hack night:

https://github.com/charlotte-ruby/projecteuler

I felt this worked out alright because it walked through how to setup a project, write the implementation, how to write tests, and get a CI to work for an app. This works best for small, simple problems.

Another way we tried was creating a repo of rubyquiz questions and having people submit answers as pull requests:

https://github.com/charlotte-ruby/rubyquiz

@kirillian and @mike both submitted pull requests and presented their solutions during a hack night. I really liked this approach because it showed multiple solutions and gave people a chance to see how someone solved a problem. Showcasing during hack nights also brought some good questions about the solutions and why these guys did things the way they did.

If we'd like to pick these back up, I'm more than happy to get us started again. I'd say let's just try one out.

**Comment by invalidusrname** [comment]
As for meetup.com costs, I've covered the first 6months of the year. After that we'll have to talk about what to do. Most people find out about the group from there. 

We also have http://charlotteruby.org that @scottned has been covering for a few years. That's linked to https://github.com/charlotte-ruby/charlotte-ruby.github.com

If we're looking for projects for folks to work on, I'd suggest updating that repo, tackling some of the existing repos under [charlotte-ruby](https://github.com/charlotte-ruby), or making something new. It'd be a good way for people to get their names out in the tech community too.

**Comment by binarymason** [comment]
Great feedback, @invalidusrname! 👍 

The common thread that I'm picking up from your experience is that **a successful meetup has a win at the end**.

If we can curate the backlog of challenges to ensure it is small enough in scope and not too difficult to achieve, **junior developers can walk away with a win and increased sense of confidence**.  That would be awesome if we can give them that. 🏅 

Another thing, we can always ask people that come in what they want and tailor things as we go along.

<hr>

Here  are the next actions I see:

**1. Get a date on the calendar starting in April.**

In the name of having numbers, I recommend having a ruby meetup every other week. I would say 1st and 3rd Tuesday of every month sounds perfect... but I see on http://skookum.com/events that the 3rd Tuesday of the month gets busy. You guys open to changing from Tuesday to Thursdays?  Then we could have an easy to remember: 1st and 3rd Thursday at Skookum. @invalidusrname. @chrishowie, @enriikke would this be possible?

**2. Start a small backlog of achievable-within-2-hours challenges**

Let's at least get five challenges listed as issues on https://github.com/charlotte-ruby/challenges/issues.  @kirillian you mind taking lead on that?

**3. Spread the word once the dates are on the calendar.**

This one is informally dependent everybody.  @chrishowie and I can take lead on taking to the boot camps once we have our dates confirmed.

<hr>

After that, we can ask for feedback and iterate on what people want/need.

**Comment by binarymason** [comment]
Also, @chrishowie -- looks like @kirillian might be able to give a talk at the library depending on the desired content. https://github.com/rollyourownruby/rollyourownruby/issues/1#issuecomment-286247925

**Comment by invalidusrname** [comment]
So I forked Holman's ama repo for [charlotte-ruby](https://github.com/charlotte-ruby/ama). Perhaps it would be a good idea to throw some of the questions asked over here, that way they get noted and other people can see them?

**Comment by binarymason** [comment]
This issue was moved to charlotte-ruby/ama#1
